<form>
    <label for="title">Título</label>
    <input id="title" type="text" />
    <label for="date">Fecha</label>
    <input id="date" type="date" />
    <label for="priority">Prioridad</label>
    <select name="priority" id="priority">
        <option value="Sin Importancia" selected>Sin importancia</option>
        <option value="Normal" selected>Normal</option>
        <option value="Importante">Importante</option>
        <option value="Urgente">Urgente</option>
    </select>
    <label for="status">Status</label>
    <select name="status" id="status">
        <option value="Por Hacer" selected>Por Hacer</option>
        <option value="En progreso">En progreso</option>
        <option value="Realizado">Realizado</option>

    </select>
</form>